# Generated by Django 3.0.6 on 2020-05-28 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('0', '---Select---'), ('1', 'SRS'), ('2', 'CR'), ('3', 'BRS'), ('4', 'Database Server Access'), ('5', 'Application Server Access'), ('6', 'Port'), ('7', 'IP'), ('8', 'Whitelisting'), ('9', 'Application Access'), ('10', 'Deployment'), ('11', 'Data Backup')], default='0', max_length=256)),
                ('request_title', models.CharField(max_length=256)),
                ('requester', models.CharField(max_length=256)),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('required_date', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, default='')),
                ('ip_required', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='0', max_length=256)),
                ('user_required', models.CharField(blank=True, choices=[('0', 'No'), ('1', 'Yes')], default='0', max_length=256)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('role', models.CharField(blank=True, choices=[('0', 'Developer'), ('1', 'Tester')], max_length=256)),
                ('database_required', models.CharField(blank=True, choices=[('0', 'No'), ('1', 'Yes')], default='0', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='IPInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=256)),
                ('port', models.CharField(blank=True, max_length=256)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AMSApp.ApprovalRequest')),
            ],
        ),
    ]
