# Generated by Django 3.0.6 on 2020-05-31 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AMSApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipinformation',
            name='approval_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_informations', to='AMSApp.ApprovalRequest'),
        ),
        migrations.CreateModel(
            name='ApprovalRequestFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='AMSApp.ApprovalRequest')),
            ],
        ),
    ]
